### ISSUE TITLE
Respond when PR opened against the wrong branch

### ISSUE THREAD

**Issue by hectorsector** [githubtraining/intro-to-html#8]
If a user opens a PR against the wrong branch, the app currently doesn't respond. We should probably respond with some guidance.

**Comment by brianamarie** [comment]
I just went through this course about 3 times. I think that we can close this issue without implementing this, because:
- The links to prompt users to open pull requests with the pre-populated branches are very effective
- We haven't had any reports of this confusing users in the forum

@hectorsector I'm going to go ahead and close this issue as a part of comms duty. If I'm missing something, or we should return to this for some reason, please reopen 😊
